<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8518bcc0-91e4-4049-bd3e-fda098c46bce</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.13.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.9" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Console.LogThemes" Version="0.4.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
    <PackageReference Include="Yarp.Telemetry.Consumption" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Temp\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Admin.Blazor\Admin.Blazor.Client\Admin.Blazor.Client.csproj" />
    <ProjectReference Include="..\Products.Shared\Products.Shared.csproj" />
    <ProjectReference Include="..\Products.Write.Application\Products.Write.Application.csproj" />
    <ProjectReference Include="..\Products.Write.Domain\Products.Write.Domain.csproj" />
    <ProjectReference Include="..\Products.Write.Infrastructure\Products.Write.Infrastructure.csproj" />
  </ItemGroup>

</Project>
