<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Products.Write.Application\Products.Write.Application.csproj" />
    <ProjectReference Include="..\Products.Write.Domain\Products.Write.Domain.csproj" />
  </ItemGroup>

</Project>
