<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CQRS\Queries\**" />
    <Compile Remove="CQRS\QueryHandlers\**" />
    <EmbeddedResource Remove="CQRS\Queries\**" />
    <EmbeddedResource Remove="CQRS\QueryHandlers\**" />
    <None Remove="CQRS\Queries\**" />
    <None Remove="CQRS\QueryHandlers\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Products.Shared\Products.Shared.csproj" />
    <ProjectReference Include="..\Products.Write.Domain\Products.Write.Domain.csproj" />
    <ProjectReference Include="..\Products.Write.Infrastructure\Products.Write.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.0-beta.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.13.0" />
    <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.9" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
  </ItemGroup>

</Project>
